[pids]
1 = "发射器"
2 = "熔炉"
3 = "黑曜石"
4 = "TNT地雷"
5 = "小发射器"
6 = "睡莲"
7 = "顺炸TNT"
8 = "生物质发电机"
9 = "阴森南瓜头"
10 = "魔术粉"
11 = "wan南瓜头"
12 = "寒冰bomb"
13 = "三线酒驾"
14 = "轮椅炮"
15 = "樱桃反弹布丁"
16 = "双向水管"
17 = "萤石粉"
[types]
1 = "金币"
2 = "皮革"
3 = "铁ignot"
4 = "黑曜石勋章"
5 = "回声碎片"
6 = "龙珠"
7 = "机械齿轮"
8 = "天狗绒毛"
9 = "光学透镜"
10 = "NIXXOR镜头"
11 = "奇迹御神签"
99889988 = "未开放等级占位材料"
